local _, rm = ...

rm.objectDB = {
	[2844] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Tattered Chest",
			esES = "Cofre Ajado",
			esMX = "Cofre Ajado",
			frFR = "Coffre En Morceaux",
			koKR = "낡은 궤짝",
			ptBR = "Baú Gasto",
			ruRU = "Побитый Сундук",
			zhCN = "破碎的箱子",
			zhTW = "破碎的箱子",
		},
		zones = {
			3524,
		},
	},
	[2845] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Tattered Chest",
			esES = "Cofre Ajado",
			esMX = "Cofre Ajado",
			frFR = "Coffre En Morceaux",
			koKR = "낡은 궤짝",
			ptBR = "Baú Gasto",
			ruRU = "Побитый Сундук",
			zhCN = "破碎的箱子",
			zhTW = "破碎的箱子",
		},
		zones = {
			3430,
		},
	},
	[3642] = {
		names = {
			deDE = "Beute Der Kolkar",
			enUS = "Kolkars Booty",
			esES = "Botín De Kolkar",
			esMX = "Botín De Kolkar",
			frFR = "Butin Des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim de Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[74448] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Macizo Grande",
			esMX = "Cofre Macizo Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			721,
			491,
			796,
		},
	},
	[75293] = {
		names = {
			deDE = "Große Ramponierte Truhe",
			enUS = "Large Battered Chest",
			esES = "Cofre Grande Abollado",
			esMX = "Cofre Grande Abollado",
			frFR = "Grand Coffre Endommagé",
			koKR = "찌그러진 대형 궤짝",
			ptBR = "Baú Desgastado Grande",
			ruRU = "Большой Побитый Сундук",
			zhCN = "破碎的大箱子",
			zhTW = "破碎的大箱子",
		},
		zones = {
			209,
			1581,
			3433,
			718,
			3525,
		},
	},
	[75295] = {
		names = {
			deDE = "Große Eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre Reforzado Con Hierro Grande",
			esMX = "Cofre Reforzado Con Hierro Grande",
			frFR = "Grand Coffre Cerclé De Fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Окованный Железом Большой Сундук",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			209,
		},
	},
	[75298] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Macizo Grande",
			esMX = "Cofre Macizo Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			209,
			719,
			717,
		},
	},
	[75299] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Macizo Grande",
			esMX = "Cofre Macizo Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			796,
		},
	},
	[75300] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Macizo Grande",
			esMX = "Cofre Macizo Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			796,
			722,
		},
	},
	[131979] = {
		names = {
			deDE = "Große Dunkelholztruhe",
			enUS = "Large Darkwood Chest",
			esES = "Cofre Grande De Leñoscuro",
			esMX = "Cofre Grande De Leñoscuro",
			frFR = "Grand Coffre De Sombrebois",
			koKR = "큰 흑단 궤짝",
			ptBR = "Baú de Lenhanegra Grande",
			ruRU = "Большой Сундук Из Темного Дерева",
			zhCN = "大型黑木箱",
			zhTW = "大型黑木箱",
		},
		zones = {
			1337,
		},
	},
	[141979] = {
		names = {
			deDE = "Antiker Schatz",
			enUS = "Ancient Treasure",
			esES = "Tesoro Antiguo",
			esMX = "Tesoro Antiguo",
			frFR = "Trésor Ancien",
			koKR = "고대의 보물",
			ptBR = "Tesouro Antigo",
			ruRU = "Древнее Сокровище",
			zhCN = "古代宝藏",
			zhTW = "古代寶藏",
		},
		zones = {
			1337,
		},
	},
	[142184] = {
		names = {
			deDE = "Truhe Des Kapitäns",
			enUS = "Captains Chest",
			esES = "Cofre Del Capitán",
			esMX = "Cofre Del Capitán",
			frFR = "Coffre Du Capitaine",
			koKR = "선장의 궤짝",
			ptBR = "Baú do Capitão",
			ruRU = "Сундук Капитана",
			zhCN = "船长的箱子",
			zhTW = "船長的箱子",
		},
		zones = {
			440,
		},
	},
	[152618] = {
		names = {
			deDE = "Beute Der Kolkar",
			enUS = "Kolkars Booty",
			esES = "Botín De Kolkar",
			esMX = "Botín De Kolkar",
			frFR = "Butin Des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim do Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[153464] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Macizo Grande",
			esMX = "Cofre Macizo Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			2557,
			1583,
			2017,
		},
	},
	[160845] = {
		names = {
			deDE = "Dunkler Kasten",
			enUS = "Dark Coffer",
			esES = "Arca Oscura",
			esMX = "Arca Oscura",
			frFR = "Coffre Sombre",
			koKR = "검은 금고",
			ptBR = "Cofre Sombrio",
			ruRU = "Черный Ящик",
			zhCN = "黑暗宝箱",
			zhTW = "黑暗寶箱",
		},
		zones = {
			1584,
		},
	},
	[173232] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
			2017,
		},
	},
	[173234] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
		},
	},
	[176325] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[176327] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[179564] = {
		names = {
			deDE = "Tribut Der Gordok",
			enUS = "Gordok Tribute",
			esES = "Tributo A Gordok",
			esMX = "Tributo A Gordok",
			frFR = "Tribut Des Gordok",
			koKR = "고르독 공물",
			ptBR = "Homenagem a Gordok",
			ruRU = "Приношения Гордока",
			zhCN = "戈多克贡品",
			zhTW = "戈多剋貢品",
		},
		zones = {
			2557,
		},
	},
	[179697] = {
		names = {
			deDE = "Arenaschatztruhe",
			enUS = "Arena Treasure Chest",
			esES = "Arqueta De La Arena",
			esMX = "Arqueta De La Arena",
			frFR = "Coffre Au Trésor De Larène",
			koKR = "투기장 보물상자",
			ruRU = "Сундук С Сокровищами Арены",
		},
		zones = {
			5287,
		},
	},
	[185584] = {
		names = {
			deDE = "Najentus Stachel",
			enUS = "Najentus Spine",
			esES = "Espinazo De Najentus",
			esMX = "Espinazo De Najentus",
			frFR = "Epine Dorsale De Najentus",
			koKR = "나젠투스 돌기",
			ptBR = "Espinho de Naj'entus",
			ruRU = "Шип Наджентуса",
			zhCN = "纳因图斯之脊",
			zhTW = "納因圖斯之脊",
		},
		zones = {
			3959,
		},
	},
	[187892] = {
		names = {
			deDE = "Eiskiste",
			enUS = "Ice Chest",
			esES = "Cofre De Hielo",
			esMX = "Cofre De Hielo",
			frFR = "Coffre De Glace",
			koKR = "얼음 궤짝",
			ptBR = "Baú de Gelo",
			ruRU = "Ледник",
		},
		zones = {
			3717,
		},
	},
	[188192] = {
		names = {
			deDE = "Eiskiste",
			enUS = "Ice Chest",
			esES = "Cofre De Hielo",
			esMX = "Cofre De Hielo",
			frFR = "Coffre De Glace",
			ruRU = "Ледник",
		},
		zones = {
			3717,
		},
	},
	[191349] = {
		names = {
			deDE = "Eregos Lager",
			enUS = "Cache Of Eregos",
			frFR = "Cache Deregos",
			koKR = "에레고스의 보관함",
			ptBR = "Cache of Eregos",
			ruRU = "Тайник Эрегоса",
		},
		zones = {
			4228,
		},
	},
	[193603] = {
		names = {
			deDE = "Eregos Lager",
			enUS = "Cache Of Eregos",
			esES = "Alijo De Eregos",
			esMX = "Alijo De Eregos",
			frFR = "Cache Deregos",
			koKR = "에레고스의 보관함",
			ptBR = "Baú de Éregos",
			ruRU = "Тайник Эрегоса",
		},
		zones = {
			4228,
		},
	},
	[194308] = {
		names = {
			deDE = "Schrein Des Winters",
			enUS = "Cache Of Winter",
			esES = "Alijo De Invierno",
			esMX = "Alijo De Invierno",
			frFR = "Cache De Lhiver",
			ptBR = "Cache of Winter",
			ruRU = "Тайник Ходира",
		},
		zones = {
			4273,
		},
	},
	[194315] = {
		names = {
			deDE = "Schrein Der Stürme",
			enUS = "Cache Of Storms",
			frFR = "Cache Des Tempêtes",
			ptBR = "Cache of Storms",
			ruRU = "Тайник Торима",
		},
		zones = {
			4273,
		},
	},
	[194327] = {
		names = {
			deDE = "Freyas Geschenk",
			enUS = "Freyas Gift",
			frFR = "Cadeau De Freya",
			ptBR = "Freya's Gift",
			ruRU = "Дар Фрейи",
			zhCN = "弗蕾亚的礼物",
			zhTW = "弗蕾亞的禮物",
		},
		zones = {
			4273,
		},
	},
	[194464] = {
		names = {
			deDE = "Ritualedelstein",
			enUS = "Ritual Gem",
			frFR = "Gemme De Rituel",
			ruRU = "Ритуальный Самоцвет",
			zhCN = "仪式宝石",
			zhTW = "儀式寶石",
		},
		zones = {
			331,
		},
	},
	[194822] = {
		names = {
			deDE = "Geschenk Des Beobachters",
			enUS = "Gift Of The Observer",
			esES = "Obsequio Del Observador",
			esMX = "Obsequio Del Observador",
			frFR = "Don De Lobservateur",
			ptBR = "Gift of the Observer",
			ruRU = "Дар Наблюдателя",
		},
		zones = {
			4273,
		},
	},
	[194958] = {
		names = {
			deDE = "Schrein Der Innovation",
			enUS = "Cache Of Innovation",
			esES = "Alijo De Innovación",
			esMX = "Alijo De Innovación",
			frFR = "Cache De Linnovation",
			ptBR = "Cache of Innovation",
			ruRU = "Склад Изобретателя",
		},
		zones = {
			4273,
		},
	},
	[195047] = {
		names = {
			deDE = "Schrein Des Lebenden Gesteins",
			enUS = "Cache Of Living Stone",
			esES = "Alijo De Piedra Viva",
			esMX = "Alijo De Piedra Viva",
			frFR = "Cache De Pierre Vivante",
			ptBR = "Baú de Pedra Viva",
			ruRU = "Ларь Из Живящего Камня",
		},
		zones = {
			4273,
		},
	},
	[195631] = {
		names = {
			deDE = "Truhe Der Champions",
			enUS = "Champions Cache",
			frFR = "Cache Des Champions",
			ptBR = "Champions' Cache",
			ruRU = "Ларь Чемпиона",
		},
		zones = {
			4722,
		},
	},
	[201724] = {
		names = {
			deDE = "Borstennackenkäfig",
			enUS = "Bristleback Cage",
			esES = "Jaula De Erizapúas",
			esMX = "Jaula De Erizapúas",
			frFR = "Cage Dos Hirsute",
			koKR = "뾰족털 우리",
			ruRU = "Клетка Дыбогривов",
		},
		zones = {
			4709,
		},
	},
	[207492] = {
		names = {
			deDE = "Stabile Schatzkiste",
			enUS = "Sturdy Treasure Chest",
			esES = "Arqueta Robusta",
			esMX = "Arqueta Robusta",
			frFR = "Coffre Solide",
			koKR = "튼튼한 보물 상자",
			ptBR = "Baú do Tesouro Resistente",
			ruRU = "Прочный Сундук С Сокровищами",
		},
		zones = {
			394,
			495,
			3537,
		},
	},
	[207493] = {
		names = {
			deDE = "Stabile Schatzkiste",
			enUS = "Sturdy Treasure Chest",
			esES = "Arqueta Robusta",
			esMX = "Arqueta Robusta",
			frFR = "Coffre Solide",
			koKR = "튼튼한 보물 상자",
			ptBR = "Baú do Tesouro Resistente",
			ruRU = "Прочный Сундук С Сокровищами",
			zhCN = "坚固的宝箱",
			zhTW = "堅固的寶箱",
		},
		zones = {
			67,
			3711,
			66,
			210,
			2817,
		},
	},
	[207528] = {
		names = {
			deDE = "Schatzkiste Aus Ahornholz",
			enUS = "Maplewood Treasure Chest",
			esES = "Arqueta De Madera De Arce",
			esMX = "Arqueta De Madera De Arce",
			frFR = "Coffre En Bois Dérable",
			koKR = "단풍나무 보물 상자",
			ptBR = "Baú do Tesouro de Bordo",
			ruRU = "Кленовый Сундук С Сокровищами",
		},
		zones = {
			65,
			495,
			3537,
			394,
		},
	},
	[207529] = {
		names = {
			deDE = "Schatzkiste Aus Ahornholz",
			enUS = "Maplewood Treasure Chest",
			esES = "Arqueta De Madera De Arce",
			esMX = "Arqueta De Madera De Arce",
			frFR = "Coffre En Bois Dérable",
			koKR = "단풍나무 보물 상자",
			ptBR = "Baú do Tesouro de Bordo",
			ruRU = "Кленовый Сундук С Сокровищами",
			zhCN = "枫木宝箱",
			zhTW = "楓木寶箱",
		},
		zones = {
			210,
			67,
		},
	},
}