local _, rm = ...

rm.objectDB = {
	[1721] = {
		names = {
			enUS = "Locked Ball And Chain",
			frFR = "Boulet Et Chaîne Verrouillés",
			deDE = "Verschlossene Kugel Und Kette",
			esES = "Cadena Con Bola De Preso",
			ruRU = "Запертые Шар И Цепь",
			ptBR = "Bola E Corrente Presas",
			zhCN = "坚固链球",
			koKR = "단단히 잠긴 족쇄",
			zhTW = "堅固鍊球",
			esMX = "Cadena Con Bola De Preso",
		},
		zones = {
			267,
		},
	},
	[2560] = {
		names = {
			enUS = "Half Buried Bottle",
			frFR = "Bouteille À Moitié Ensevelie",
			deDE = "Halb Vergrabene Flasche",
			esES = "Botella Semienterrada",
			ruRU = "Полузакопанная Бутылка",
			ptBR = "Garrafa Semienterrada",
			zhCN = "半埋的瓶子",
			koKR = "반쯤 묻힌 병",
			zhTW = "半埋的瓶子",
			esMX = "Botella Semienterrada",
		},
		zones = {
			33,
		},
	},
	[2844] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			esMX = "Cofre Ajado",
		},
		zones = {
			3524,
		},
	},
	[2845] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
			esMX = "Cofre Ajado",
		},
		zones = {
			3430,
		},
	},
	[2846] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			esMX = "Cofre Ajado",
		},
		zones = {
			3525,
		},
	},
	[2847] = {
		names = {
			enUS = "Tattered Chest",
		},
		zones = {
			3433,
		},
	},
	[2849] = {
		names = {
			enUS = "Battered Chest",
			frFR = "Coffre Endommagé",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Maltrecho",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Desgastado",
			zhCN = "破损的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破損的箱子",
			esMX = "Cofre Maltrecho",
		},
		zones = {
			44,
			148,
			406,
			17,
			3525,
			38,
			130,
			3433,
			331,
			40,
		},
	},
	[2850] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			44,
			11,
			10,
			331,
			406,
			267,
			17,
		},
	},
	[2852] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			10,
			400,
			11,
			331,
			267,
		},
	},
	[2855] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			36,
			33,
			405,
			45,
			267,
			400,
		},
	},
	[2857] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			45,
			405,
			36,
			15,
			8,
			3,
			33,
		},
	},
	[3642] = {
		names = {
			enUS = "Kolkars Booty",
			frFR = "Butin Des Kolkar",
			deDE = "Beute Der Kolkar",
			esES = "Botín De Kolkar",
			ruRU = "Добыча Колкара",
			ptBR = "Butim De Kolkar",
			zhCN = "科卡尔的战利品",
			koKR = "콜카르 노획물 궤짝",
			zhTW = "科卡爾的戰利品",
			esMX = "Botín De Kolkar",
		},
		zones = {
			17,
		},
	},
	[3714] = {
		names = {
			enUS = "Alliance Strongbox",
			frFR = "Coffre De Lalliance",
			deDE = "Geldkassette Der Allianz",
			esES = "Caja Fuerte De La Alianza",
			ruRU = "Сейф Альянса",
			ptBR = "Caixa Forte Da Aliança",
			zhCN = "联盟保险箱",
			koKR = "얼라이언스 금고",
			esMX = "Caja Fuerte De La Alianza",
		},
		zones = {
			17,
		},
	},
	[3715] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
		},
		zones = {
			267,
			406,
			17,
		},
	},
	[4096] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
		},
		zones = {
			267,
		},
	},
	[4149] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			33,
			440,
			51,
			8,
			15,
			47,
			3,
		},
	},
	[74447] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
		},
		zones = {
			721,
			491,
			796,
			717,
		},
	},
	[74448] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Macizo Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
		},
		zones = {
			721,
			491,
		},
	},
	[75293] = {
		names = {
			enUS = "Large Battered Chest",
			frFR = "Grand Coffre Endommagé",
			deDE = "Große Ramponierte Truhe",
			esES = "Cofre Grande Abollado",
			ruRU = "Большой Побитый Сундук",
			ptBR = "Baú Desgastado Grande",
			zhCN = "破碎的大箱子",
			koKR = "낡은 대형 궤짝",
			zhTW = "破碎的大箱子",
			esMX = "Cofre Grande Abollado",
		},
		zones = {
			3525,
			3433,
			2597,
			209,
			1581,
			718,
		},
	},
	[75295] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
			zhTW = "大型鐵箍儲物箱",
			esMX = "Cofre Reforzado Con Hierro Grande",
		},
		zones = {
			719,
			209,
			717,
		},
	},
	[75296] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
		},
		zones = {
			796,
		},
	},
	[75297] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
			zhTW = "大型鐵箍箱子",
		},
		zones = {
			722,
			796,
		},
	},
	[75298] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Macizo Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
			esMX = "Cofre Macizo Grande",
		},
		zones = {
			2597,
			719,
			209,
			717,
		},
	},
	[75299] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Macizo Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
		},
		zones = {
			2597,
			796,
		},
	},
	[75300] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Macizo Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
		},
		zones = {
			2597,
			722,
			796,
		},
	},
	[105578] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
		},
		zones = {
			45,
		},
	},
	[105579] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
			esMX = "Cofre Ajado",
		},
		zones = {
			36,
			45,
		},
	},
	[105581] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "破碎的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
		},
		zones = {
			45,
		},
	},
	[106318] = {
		names = {
			enUS = "Battered Chest",
			frFR = "Coffre Endommagé",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Maltrecho",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Desgastado",
			zhCN = "破损的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破損的箱子",
			esMX = "Cofre Maltrecho",
		},
		zones = {
			14,
			12,
			215,
			1,
			141,
			85,
		},
	},
	[106319] = {
		names = {
			enUS = "Battered Chest",
			frFR = "Coffre Endommagé",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Maltrecho",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Desgastado",
			zhCN = "破损的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破損的箱子",
			esMX = "Cofre Maltrecho",
		},
		zones = {
			40,
			38,
			17,
			130,
			3433,
			148,
		},
	},
	[111095] = {
		names = {
			enUS = "Tattered Chest",
			frFR = "Coffre En Morceaux",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Ajado",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Gasto",
			zhCN = "联盟宝箱",
			koKR = "낡은 궤짝",
			zhTW = "破爛的箱子",
			esMX = "Cofre Ajado",
		},
		zones = {
			130,
			3433,
			17,
		},
	},
	[131978] = {
		names = {
			enUS = "Large Mithril Bound Chest",
			frFR = "Grand Coffre Cerclé De Mithril",
			deDE = "Große Mithrilbeschlagene Truhe",
			esES = "Cofre Reforzado Con Mitril Grande",
			ruRU = "Большой Сундук Окованный Мифрилом",
			ptBR = "Baú Grande Reforçado Com Mithril",
			zhCN = "大型秘银储物箱",
			koKR = "큰 미스릴 궤짝",
			zhTW = "大型祕銀儲物箱",
		},
		zones = {
			1337,
		},
	},
	[131979] = {
		names = {
			enUS = "Large Darkwood Chest",
			frFR = "Grand Coffre De Sombrebois",
			deDE = "Große Dunkelholztruhe",
			esES = "Cofre Grande De Leñoscuro",
			ruRU = "Большой Сундук Темного Леса",
			ptBR = "Baú De Lenhanegra Grande",
			zhCN = "大型黑木箱",
			koKR = "큰 흑단 궤짝",
			zhTW = "大型黑木箱",
		},
		zones = {
			1337,
		},
	},
	[141979] = {
		names = {
			enUS = "Ancient Treasure",
			frFR = "Trésor Ancien",
			deDE = "Antiker Schatz",
			esES = "Tesoro Antiguo",
			ruRU = "Древнее Сокровище",
			ptBR = "Tesouro Antigo",
			zhCN = "古代宝藏",
			koKR = "고대의 보물",
			zhTW = "古代寶藏",
		},
		zones = {
			1337,
		},
	},
	[142184] = {
		names = {
			enUS = "Captains Chest",
			frFR = "Coffre Du Capitaine",
			deDE = "Truhe Des Kapitäns",
			esES = "Cofre Del Capitán",
			ruRU = "Сундук Капитана",
			ptBR = "Baú Do Capitão",
			zhCN = "船长的箱子",
			koKR = "선장의 궤짝",
			zhTW = "船長的箱子",
			esMX = "Cofre Del Capitán",
		},
		zones = {
			440,
		},
	},
	[152608] = {
		names = {
			enUS = "Kolkars Booty",
			frFR = "Butin Des Kolkar",
			deDE = "Beute Der Kolkar",
			esES = "Botín De Kolkar",
			ruRU = "Добыча Колкара",
			ptBR = "Butim Do Kolkar",
			zhCN = "科卡尔的战利品",
			koKR = "콜카르 노획물 궤짝",
			zhTW = "科卡爾的戰利品",
			esMX = "Botín De Kolkar",
		},
		zones = {
			17,
		},
	},
	[152618] = {
		names = {
			enUS = "Kolkars Booty",
			frFR = "Butin Des Kolkar",
			deDE = "Beute Der Kolkar",
			esES = "Botín De Kolkar",
			ruRU = "Добыча Колкара",
			ptBR = "Butim Do Kolkar",
			zhCN = "科卡尔的战利品",
			koKR = "콜카르 노획물 궤짝",
			zhTW = "科卡爾的戰利品",
			esMX = "Botín De Kolkar",
		},
		zones = {
			17,
		},
	},
	[153451] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			47,
			16,
			4,
			440,
		},
	},
	[153453] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			46,
			16,
			28,
			139,
		},
	},
	[153454] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Macizo",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			139,
			618,
		},
	},
	[153463] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
		},
		zones = {
			28,
		},
	},
	[153464] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Macizo Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
		},
		zones = {
			2597,
			1583,
			2557,
			2017,
		},
	},
	[153468] = {
		names = {
			enUS = "Large Mithril Bound Chest",
			frFR = "Grand Coffre Cerclé De Mithril",
			deDE = "Große Mithrilbeschlagene Truhe",
			esES = "Cofre Reforzado Con Mitril Grande",
			ruRU = "Большой Сундук Окованный Мифрилом",
			ptBR = "Baú Grande Reforçado Com Mithril",
			zhCN = "大型秘银储物箱",
			koKR = "큰 미스릴 궤짝",
			zhTW = "大型秘銀箱子",
		},
		zones = {
			28,
		},
	},
	[153469] = {
		names = {
			enUS = "Large Mithril Bound Chest",
			frFR = "Grand Coffre Cerclé De Mithril",
			deDE = "Große Mithrilbeschlagene Truhe",
			esES = "Cofre Reforzado Con Mitril Grande",
			ruRU = "Большой Сундук Окованный Мифрилом",
			ptBR = "Baú Grande Reforçado Com Mithril",
			zhCN = "大型秘银储物箱",
			koKR = "큰 미스릴 궤짝",
			zhTW = "大型祕銀儲物箱",
		},
		zones = {
			1583,
			2557,
			2017,
		},
	},
	[160836] = {
		names = {
			enUS = "Relic Coffer",
			frFR = "Coffre Aux Reliques",
			deDE = "Reliktkasten",
			esES = "Arca De Reliquias",
			ruRU = "Реликварий",
			ptBR = "Arca De Relíquia",
			zhCN = "古物宝库",
			koKR = "유물 금고",
			zhTW = "古物寶庫",
		},
		zones = {
			2597,
			1584,
			3277,
		},
	},
	[160845] = {
		names = {
			enUS = "Dark Coffer",
			frFR = "Coffre Sombre",
			deDE = "Dunkler Kasten",
			esES = "Arca Oscura",
			ruRU = "Черный Ящик",
			ptBR = "Cofre Sombrio",
			zhCN = "黑暗宝箱",
			koKR = "검은 금고",
			zhTW = "黑暗寶箱",
		},
	},
	[173232] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
			2017,
		},
	},
	[173234] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
		},
	},
	[176224] = {
		names = {
			enUS = "Supply Crate",
			frFR = "Caisse De Fournitures",
			deDE = "Vorratskiste",
			esES = "Cajón De Suministros",
			ruRU = "Ящик С Припасами",
			ptBR = "Caixote De Suprimentos",
			zhCN = "补给箱",
			koKR = "보급품 상자",
			zhTW = "補給木箱",
		},
		zones = {
			2017,
		},
	},
	[176325] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[176327] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[179501] = {
		names = {
			enUS = "Knot Thimblejacks Cache",
			frFR = "Réserve De Noué Dédodevie",
			deDE = "Knot Zwingschraubs Behälter",
			esES = "Alijo De Knot Thimblejack",
			ruRU = "Тайник Уззла Наперстяка",
			ptBR = "Tesouro Do Fiapo Agulhacerta",
			zhCN = "诺特 希姆加克的储物箱",
			koKR = "노트 팀블잭의 은닉품",
			zhTW = "諾特 希姆加克的儲物箱",
		},
		zones = {
			2557,
		},
	},
	[179564] = {
		names = {
			enUS = "Gordok Tribute",
			frFR = "Tribut Des Gordok",
			deDE = "Tribut Der Gordok",
			esES = "Tributo A Gordok",
			ruRU = "Приношения Гордока",
			ptBR = "Homenagem A Gordok",
			zhCN = "戈多克贡品",
			koKR = "고르독 공물",
			zhTW = "戈多克貢品",
		},
		zones = {
			2557,
		},
	},
	[179697] = {
		names = {
			enUS = "Arena Treasure Chest",
			frFR = "Coffre Au Trésor De Larène",
			deDE = "Arenaschatztruhe",
			esES = "Cofre Del Tesoro De La Arena",
			ruRU = "Сундук Арены С Сокровищами",
			koKR = "투기장 보물상자",
			zhTW = "競技場財寶箱",
			esMX = "Arqueta De La Arena",
		},
		zones = {
			33,
		},
	},
	[181798] = {
		names = {
			enUS = "Fel Iron Chest",
			frFR = "Coffre En Gangrefer",
			deDE = "Teufelseisentruhe",
			esES = "Cofre De Hierro Vil",
			ruRU = "Сундук Из Оскверненного Железа",
			ptBR = "Baú De Ferrovil",
			zhCN = "魔铁宝箱",
			koKR = "지옥무쇠 궤짝",
			zhTW = "魔鐵箱",
			esMX = "Cofre De Hierro Vil",
		},
		zones = {
			3483,
			3521,
			3519,
		},
	},
	[181804] = {
		names = {
			enUS = "Felsteel Chest",
			frFR = "Coffre En Gangracier",
			deDE = "Teufelsstahltruhe",
			esES = "Cofre De Acero Vil",
			ruRU = "Сундук Из Оскверненной Стали",
			ptBR = "Baú De Açovil",
			zhCN = "魔钢宝箱",
			koKR = "지옥강철 궤짝",
			zhTW = "魔鋼箱",
			esMX = "Cofre De Acero Vil",
		},
		zones = {
			3520,
			3523,
			3518,
		},
	},
	[185584] = {
		names = {
			enUS = "Najentus Spine",
			frFR = "Epine Dorsale De Najentus",
			deDE = "Najentus Stachel",
			esES = "Espinazo De Najentus",
			ruRU = "Шип Наджентуса",
			ptBR = "Espinho De Najentus",
			zhCN = "纳因图斯之脊",
			koKR = "나젠투스 돌기",
		},
		zones = {
			3959,
		},
	},
}