local _, rm = ...

rm.objectDB = {
	[2560] = {
		names = {
			enUS = "Half Buried Bottle",
			frFR = "Bouteille À Moitié Ensevelie",
			deDE = "Halb Vergrabene Flasche",
			esES = "Botella Semienterrada",
			ruRU = "Полузакопанная Бутылка",
			ptBR = "Garrafa Semienterrada",
			zhCN = "半埋的瓶子",
			koKR = "반쯤 묻힌 병",
			esMX = "Botella Semienterrada",
		},
		zones = {
			33,
		},
	},
	[2849] = {
		names = {
			enUS = "Battered Chest",
			frFR = "Coffre Endommagé",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Maltrecho",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Desgastado",
			zhCN = "破损的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破損的箱子",
			esMX = "Cofre Maltrecho",
		},
		zones = {
			44,
			148,
			406,
			38,
			17,
			331,
			130,
			40,
		},
	},
	[2850] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			44,
			11,
			10,
			331,
			406,
			267,
			17,
		},
	},
	[2852] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			10,
			331,
			400,
			11,
			267,
		},
	},
	[2855] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			36,
			33,
			405,
			45,
			267,
			400,
		},
	},
	[2857] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			45,
			405,
			36,
			15,
			8,
			3,
			33,
		},
	},
	[3642] = {
		names = {
			enUS = "Kolkars Booty",
			frFR = "Butin Des Kolkar",
			deDE = "Kolkars Beute",
			esES = "Botín Kolkar",
			ruRU = "Добыча Колкара",
			ptBR = "Butim De Kolkar",
			zhCN = "科卡尔的战利品",
			koKR = "콜카르 노획물 궤짝",
			zhTW = "科卡爾的戰利品",
			esMX = "Botín De Kolkar",
		},
		zones = {
			17,
		},
	},
	[3714] = {
		names = {
			enUS = "Alliance Strongbox",
			frFR = "Coffre De Lalliance",
			deDE = "Geldkassette Der Allianz",
			esES = "Caja Fuerte De La Alianza",
			ruRU = "Сейф Альянса",
			ptBR = "Caixa Forte Da Aliança",
			zhCN = "联盟保险箱",
			koKR = "얼라이언스 금고",
			zhTW = "聯盟保險箱",
			esMX = "Caja Fuerte De La Alianza",
		},
		zones = {
			17,
		},
	},
	[3715] = {
		names = {
			enUS = "Alliance Chest",
			frFR = "Coffre De Lalliance",
			deDE = "Truhe Der Allianz",
			esES = "Cofre De La Alianza",
			ruRU = "Сундук Альянса",
			ptBR = "Baú Da Aliança",
			zhCN = "联盟宝箱",
			koKR = "얼라이언스 궤짝",
			zhTW = "聯盟寶箱",
			esMX = "Cofre De La Alianza",
		},
		zones = {
			267,
			406,
			17,
		},
	},
	[4096] = {
		names = {
			enUS = "Alliance Chest",
			frFR = "Coffre De Lalliance",
			deDE = "Truhe Der Allianz",
			esES = "Cofre De La Alianza",
			ruRU = "Сундук Альянса",
			ptBR = "Baú Da Aliança",
			zhCN = "联盟宝箱",
			koKR = "얼라이언스 궤짝",
			zhTW = "聯盟寶箱",
			esMX = "Cofre De La Alianza",
		},
		zones = {
			267,
		},
	},
	[4149] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			33,
			51,
			440,
			8,
			15,
			47,
			3,
		},
	},
	[74447] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
			esMX = "Cofre Reforzado Con Hierro Grande",
		},
		zones = {
			721,
			491,
		},
	},
	[74448] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			esMX = "Cofre Macizo Grande",
		},
		zones = {
			721,
			491,
		},
	},
	[75293] = {
		names = {
			enUS = "Large Battered Chest",
			frFR = "Grand Coffre Endommagé",
			deDE = "Große Ramponierte Truhe",
			esES = "Cofre Grande Abollado",
			ruRU = "Большой Побитый Сундук",
			ptBR = "Baú Desgastado Grande",
			zhCN = "破碎的大箱子",
			koKR = "낡은 대형 궤짝",
			zhTW = "破碎的大箱子",
			esMX = "Cofre Grande Abollado",
		},
		zones = {
			2597,
			209,
			1581,
			718,
		},
	},
	[75295] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
			zhTW = "大型鐵箍儲物箱",
			esMX = "Cofre Reforzado Con Hierro Grande",
		},
		zones = {
			719,
			209,
			717,
		},
	},
	[75296] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			796,
		},
	},
	[75297] = {
		names = {
			enUS = "Large Iron Bound Chest",
			frFR = "Grand Coffre Cerclé De Fer",
			deDE = "Große Eisenbeschlagene Truhe",
			esES = "Cofre Reforzado Con Hierro Grande",
			ruRU = "Большой Сундук Окованный Железом",
			ptBR = "Baú Grande Reforçado Com Ferro",
			zhCN = "大型铁箍储物箱",
			koKR = "큰 철제 궤짝",
			zhTW = "大型鐵箍儲物箱",
			esMX = "Cofre Reforzado Con Hierro Grande",
		},
		zones = {
			722,
			796,
		},
	},
	[75298] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
			esMX = "Cofre Macizo Grande",
		},
		zones = {
			2597,
			719,
			209,
			717,
			3277,
		},
	},
	[75299] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
			esMX = "Cofre Macizo Grande",
		},
		zones = {
			2597,
			796,
		},
	},
	[75300] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
			esMX = "Cofre Macizo Grande",
		},
		zones = {
			2597,
			722,
			796,
		},
	},
	[105578] = {
		names = {
			enUS = "Horde Chest",
			frFR = "Coffre De La Horde",
			deDE = "Truhe Der Horde",
			esES = "Cofre De La Horda",
			ruRU = "Сундук Орды",
			ptBR = "Baú Da Horda",
			zhCN = "部落储物箱",
			koKR = "호드 궤짝",
			zhTW = "部落儲物箱",
			esMX = "Cofre De La Horda",
		},
		zones = {
			45,
		},
	},
	[105579] = {
		names = {
			enUS = "Alliance Chest",
			frFR = "Coffre De Lalliance",
			deDE = "Truhe Der Allianz",
			esES = "Cofre De La Alianza",
			ruRU = "Сундук Альянса",
			ptBR = "Baú Da Aliança",
			zhCN = "联盟宝箱",
			koKR = "얼라이언스 궤짝",
			zhTW = "聯盟寶箱",
			esMX = "Cofre De La Alianza",
		},
		zones = {
			36,
			45,
		},
	},
	[105581] = {
		names = {
			enUS = "Alliance Chest",
			frFR = "Coffre De Lalliance",
			deDE = "Truhe Der Allianz",
			esES = "Cofre De La Alianza",
			ruRU = "Сундук Альянса",
			ptBR = "Baú Da Aliança",
			zhCN = "联盟宝箱",
			koKR = "얼라이언스 궤짝",
			zhTW = "聯盟寶箱",
			esMX = "Cofre De La Alianza",
		},
		zones = {
			45,
		},
	},
	[106318] = {
		names = {
			enUS = "Battered Chest",
			frFR = "Coffre Endommagé",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Maltrecho",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Desgastado",
			zhCN = "破损的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破損的箱子",
			esMX = "Cofre Maltrecho",
		},
		zones = {
			14,
			12,
			215,
			1,
			141,
			85,
		},
	},
	[106319] = {
		names = {
			enUS = "Battered Chest",
			frFR = "Coffre Endommagé",
			deDE = "Ramponierte Truhe",
			esES = "Cofre Maltrecho",
			ruRU = "Побитый Сундук",
			ptBR = "Baú Desgastado",
			zhCN = "破损的箱子",
			koKR = "낡은 궤짝",
			zhTW = "破損的箱子",
			esMX = "Cofre Maltrecho",
		},
		zones = {
			40,
			38,
			17,
			130,
			148,
		},
	},
	[111095] = {
		names = {
			enUS = "Alliance Chest",
			frFR = "Coffre De Lalliance",
			deDE = "Truhe Der Allianz",
			esES = "Cofre De La Alianza",
			ruRU = "Сундук Альянса",
			ptBR = "Baú Da Aliança",
			zhCN = "联盟宝箱",
			koKR = "얼라이언스 궤짝",
			zhTW = "聯盟寶箱",
			esMX = "Cofre De La Alianza",
		},
		zones = {
			130,
			17,
		},
	},
	[128308] = {
		names = {
			enUS = "Shallow Grave",
			frFR = "Tombe Peu Profonde",
			deDE = "Flaches Grab",
			esES = "Tumba Poco Profunda",
			ruRU = "Неглубокая Могила",
			ptBR = "Cova Rasa",
			zhCN = "浅墓穴",
			koKR = "얕은 무덤",
			esMX = "Tumba Poco Profunda",
		},
		zones = {
			2597,
			3358,
			3277,
			1176,
		},
	},
	[128403] = {
		names = {
			enUS = "Shallow Grave",
			frFR = "Tombe Peu Profonde",
			deDE = "Flaches Grab",
			esES = "Tumba Poco Profunda",
			ruRU = "Неглубокая Могила",
			ptBR = "Cova Rasa",
			zhCN = "浅墓穴",
			koKR = "얕은 무덤",
			esMX = "Tumba Poco Profunda",
		},
		zones = {
			2597,
			3358,
			3277,
			1176,
		},
	},
	[131979] = {
		names = {
			enUS = "Large Darkwood Chest",
			frFR = "Grand Coffre De Sombrebois",
			deDE = "Große Dunkelholztruhe",
			esES = "Cofre Grande De Leñoscuro",
			ruRU = "Большой Сундук Темного Леса",
			ptBR = "Baú De Lenhanegra Grande",
			zhCN = "大型黑木箱",
			koKR = "큰 흑단 궤짝",
			zhTW = "大型黑木箱",
			esMX = "Cofre Grande De Leñoscuro",
		},
		zones = {
			1337,
		},
	},
	[141596] = {
		names = {
			enUS = "Witch Doctors Chest",
			frFR = "Coffre Du Sorcier Docteur",
			deDE = "Hexendoktors Truhe",
			esES = "Cofre Del Médico Brujo",
			ruRU = "Сундук Знахаря",
			ptBR = "Baú Do Mandingueiro",
			zhCN = "巫医的箱子",
			koKR = "의술사의 궤짝",
			esMX = "Cofre Del Médico Brujo",
		},
		zones = {
			2597,
			1176,
		},
	},
	[141979] = {
		names = {
			enUS = "Ancient Treasure",
			frFR = "Trésor Ancien",
			deDE = "Antiker Schatz",
			esES = "Tesoro Antiguo",
			ruRU = "Древнее Сокровище",
			ptBR = "Tesouro Antigo",
			zhCN = "古代宝藏",
			koKR = "고대의 보물",
			zhTW = "古代寶藏",
			esMX = "Tesoro Antiguo",
		},
		zones = {
			1337,
		},
	},
	[142184] = {
		names = {
			enUS = "Captains Chest",
			frFR = "Coffre Du Capitaine",
			deDE = "Truhe Des Käpt Ns",
			esES = "Cofre Del Capitán",
			ruRU = "Сундук Капитана",
			ptBR = "Baú Do Capitão",
			zhCN = "船长的箱子",
			koKR = "선장의 궤짝",
			esMX = "Cofre Del Capitán",
		},
		zones = {
			440,
		},
	},
	[152608] = {
		names = {
			enUS = "Kolkars Booty",
			frFR = "Butin Des Kolkar",
			deDE = "Kolkars Beute",
			esES = "Botín Kolkar",
			ruRU = "Добыча Колкара",
			ptBR = "Butim Do Kolkar",
			zhCN = "科卡尔的战利品",
			koKR = "콜카르 노획물 궤짝",
			zhTW = "科卡爾的戰利品",
			esMX = "Botín De Kolkar",
		},
		zones = {
			17,
		},
	},
	[152618] = {
		names = {
			enUS = "Kolkars Booty",
			frFR = "Butin Des Kolkar",
			deDE = "Kolkars Beute",
			esES = "Botín Kolkar",
			ruRU = "Добыча Колкара",
			ptBR = "Butim Do Kolkar",
			zhCN = "科卡尔的战利品",
			koKR = "콜카르 노획물 궤짝",
			zhTW = "科卡爾的戰利品",
			esMX = "Botín De Kolkar",
		},
		zones = {
			17,
		},
	},
	[153451] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			47,
			16,
			4,
			440,
		},
	},
	[153453] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			46,
			16,
			28,
			139,
		},
	},
	[153454] = {
		names = {
			enUS = "Solid Chest",
			frFR = "Coffre Solide",
			deDE = "Robuste Truhe",
			esES = "Cofre Sólido",
			ruRU = "Добротный Сундук",
			ptBR = "Baú Sólido",
			zhCN = "坚固的箱子",
			koKR = "단단한 궤짝",
			zhTW = "堅固的箱子",
			esMX = "Cofre Macizo",
		},
		zones = {
			139,
			618,
		},
	},
	[153463] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
		},
		zones = {
			28,
		},
	},
	[153464] = {
		names = {
			enUS = "Large Solid Chest",
			frFR = "Grand Coffre Solide",
			deDE = "Große Robuste Truhe",
			esES = "Cofre Sólido Grande",
			ruRU = "Большой Добротный Сундук",
			ptBR = "Baú Grande Sólido",
			zhCN = "坚固的大箱子",
			koKR = "크고 단단한 궤짝",
			zhTW = "堅固的大箱子",
			esMX = "Cofre Macizo Grande",
		},
		zones = {
			2597,
			1583,
			2557,
			2017,
		},
	},
	[153468] = {
		names = {
			enUS = "Large Mithril Bound Chest",
			frFR = "Grand Coffre Cerclé De Mithril",
			deDE = "Große Mithrilbeschlagene Truhe",
			esES = "Cofre Reforzado Con Mitril Grande",
			ruRU = "Большой Сундук Окованный Мифрилом",
			ptBR = "Baú Grande Reforçado Com Mithril",
			zhCN = "大型秘银储物箱",
			koKR = "큰 미스릴 궤짝",
			zhTW = "大型祕銀儲物箱",
			esMX = "Cofre Reforzado Con Mitril Grande",
		},
		zones = {
			28,
		},
	},
	[153469] = {
		names = {
			enUS = "Large Mithril Bound Chest",
			frFR = "Grand Coffre Cerclé De Mithril",
			deDE = "Große Mithrilbeschlagene Truhe",
			esES = "Cofre Reforzado Con Mitril Grande",
			ruRU = "Большой Сундук Окованный Мифрилом",
			ptBR = "Baú Grande Reforçado Com Mithril",
			zhCN = "大型秘银储物箱",
			koKR = "큰 미스릴 궤짝",
			zhTW = "大型祕銀儲物箱",
			esMX = "Cofre Reforzado Con Mitril Grande",
		},
		zones = {
			1583,
			2557,
			2017,
		},
	},
	[160836] = {
		names = {
			enUS = "Relic Coffer",
			frFR = "Coffre Aux Reliques",
			deDE = "Reliktkasten",
			esES = "Arca De Reliquias",
			ruRU = "Реликварий",
			ptBR = "Arca De Relíquia",
			zhCN = "古物宝库",
			koKR = "유물 금고",
			zhTW = "古物寶庫",
			esMX = "Arca De Reliquias",
		},
		zones = {
			2597,
			1584,
			3277,
		},
	},
	[160845] = {
		names = {
			enUS = "Dark Coffer",
			frFR = "Coffre Sombre",
			deDE = "Dunkler Kasten",
			esES = "Arca Oscura",
			ruRU = "Черный Ящик",
			ptBR = "Cofre Sombrio",
			zhCN = "黑暗宝箱",
			koKR = "검은 금고",
			zhTW = "黑暗寶箱",
			esMX = "Arca Oscura",
		},
	},
	[173232] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
			esMX = "Diseños De Herrería",
		},
		zones = {
			1584,
		},
	},
	[173234] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
			esMX = "Diseños De Herrería",
		},
		zones = {
			1584,
		},
	},
	[176224] = {
		names = {
			enUS = "Supply Crate",
			frFR = "Caisse De Fournitures",
			deDE = "Vorratskiste",
			esES = "Cajón De Provisiones",
			ruRU = "Ящик С Припасами",
			ptBR = "Caixote De Suprimentos",
			zhCN = "补给箱",
			koKR = "보급품 상자",
			zhTW = "補給箱",
			esMX = "Cajón De Suministros",
		},
		zones = {
			2597,
			2017,
		},
	},
	[176325] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
			esMX = "Diseños De Herrería",
		},
		zones = {
			2017,
		},
	},
	[176327] = {
		names = {
			enUS = "Blacksmithing Plans",
			frFR = "Plans De Forgeron",
			deDE = "Schmiedekunstpläne",
			esES = "Diseños De Herrería",
			ruRU = "Чертежи Кузнечного Дела",
			ptBR = "Instruções De Ferraria",
			zhCN = "锻造设计图",
			koKR = "대장기술 도면",
			zhTW = "鍛造設計圖",
			esMX = "Diseños De Herrería",
		},
		zones = {
			2017,
		},
	},
	[179501] = {
		names = {
			enUS = "Knot Thimblejacks Cache",
			frFR = "Réserve De Knot Thimblejack",
			deDE = "Knot Thimblejacks Behälter",
			esES = "Alijo De Knot Thimblejack",
			ruRU = "Тайник Уззла Наперстяка",
			ptBR = "Tesouro Do Fiapo Agulhacerta",
			zhCN = "诺特 希姆加克的储物箱",
			koKR = "노트 팀블잭의 은닉품",
			zhTW = "諾特 希姆加克的儲物箱",
			esMX = "Alijo De Knot Thimblejack",
		},
		zones = {
			2557,
		},
	},
	[179564] = {
		names = {
			enUS = "Gordok Tribute",
			frFR = "Tribut Des Gordok",
			deDE = "Tribut Der Gordok",
			esES = "Tributo A Gordok",
			ruRU = "Приношения Клана Гордок",
			ptBR = "Homenagem A Gordok",
			zhCN = "戈多克贡品",
			koKR = "고르독 공물",
			zhTW = "戈多克貢品",
			esMX = "Tributo A Gordok",
		},
	},
	[179697] = {
		names = {
			enUS = "Arena Treasure Chest",
			frFR = "Coffre Au Trésor De Larène",
			deDE = "Arenaschatztruhe",
			esES = "Cofre Del Tesoro De La Arena",
			ruRU = "Сундук Арены С Сокровищами",
			koKR = "투기장 보물상자",
			esMX = "Arqueta De La Arena",
		},
		zones = {
			33,
		},
	},
	[404352] = {
		names = {
			enUS = "Artifact Storage",
			frFR = "Entrepôt De L Artéfact",
			deDE = "Artefaktlagertruhe",
			esES = "Depósito Del Artefacto",
			ruRU = "Хранилище Артефактов",
			koKR = "유물 보관함",
			esMX = "Depósito De Artefactos",
		},
		zones = {
			215,
		},
	},
	[407734] = {
		names = {
			enUS = "Gnarlpine Cache",
			frFR = "Cache Pin Tordu",
			deDE = "Knarzklauenkiste",
			esES = "Alijo Tuercepinos",
			ruRU = "Тайник Кривой Сосны",
			ptBR = "Baú Masca Pinho",
			koKR = "나무옹이 보관함",
		},
		zones = {
			141,
		},
	},
	[415614] = {
		names = {
			enUS = "Mysterious Formulae",
			frFR = "Formules Mystérieuses",
			esES = "Fórmulas Misteriosas",
			ruRU = "Таинственные Формулы",
		},
		zones = {
			719,
		},
	},
}