local _, rm = ...

rm.objectDB = {
	[2560] = {
		names = {
			deDE = "Halb Vergrabene Flasche",
			enUS = "Half Buried Bottle",
			esES = "Botella Semienterrada",
			esMX = "Botella Semienterrada",
			frFR = "Bouteille À Moitié Ensevelie",
			koKR = "반쯤 묻힌 병",
			ptBR = "Garrafa Semienterrada",
			ruRU = "Полузакопанная Бутылка",
			zhCN = "半埋的瓶子",
			zhTW = "半埋的瓶子",
		},
		zones = {
			33,
		},
	},
	[2849] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Battered Chest",
			esES = "Cofre Maltrecho",
			esMX = "Cofre Maltrecho",
			frFR = "Coffre Endommagé",
			koKR = "낡은 궤짝",
			ptBR = "Baú Desgastado",
			ruRU = "Побитый Сундук",
			zhCN = "破损的箱子",
			zhTW = "破損的箱子",
		},
		zones = {
			44,
			148,
			406,
			17,
			38,
			130,
			331,
			40,
		},
	},
	[2850] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			11,
			44,
			10,
			331,
			406,
			267,
			17,
		},
	},
	[2852] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			10,
			400,
			11,
			331,
			267,
		},
	},
	[2855] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			36,
			33,
			405,
			45,
			267,
			400,
		},
	},
	[2857] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			45,
			405,
			36,
			15,
			3,
			8,
			33,
		},
	},
	[3642] = {
		names = {
			deDE = "Kolkars Beute",
			enUS = "Kolkars Booty",
			esES = "Botín Kolkar",
			esMX = "Botín Kolkar",
			frFR = "Butin Des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim de Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[3714] = {
		names = {
			deDE = "Geldkassette Der Allianz",
			enUS = "Alliance Strongbox",
			esES = "Caja Fuerte De La Alianza",
			esMX = "Caja Fuerte De La Alianza",
			frFR = "Coffre De Lalliance",
			koKR = "얼라이언스 금고",
			ptBR = "Caixa-forte da Aliança",
			ruRU = "Сейф Альянса",
			zhCN = "联盟保险箱",
			zhTW = "聯盟保險箱",
		},
		zones = {
			17,
		},
	},
	[3715] = {
		names = {
			deDE = "Truhe Der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre De La Alianza",
			esMX = "Cofre De La Alianza",
			frFR = "Coffre De Lalliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			267,
			406,
			17,
		},
	},
	[4096] = {
		names = {
			deDE = "Truhe Der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre De La Alianza",
			esMX = "Cofre De La Alianza",
			frFR = "Coffre De Lalliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			267,
		},
	},
	[4149] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			33,
			51,
			440,
			8,
			15,
			47,
			3,
		},
	},
	[74447] = {
		names = {
			deDE = "Große Eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre Reforzado Con Hierro Grande",
			esMX = "Cofre Reforzado Con Hierro Grande",
			frFR = "Grand Coffre Cerclé De Fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой Сундук Окованный Железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			491,
		},
	},
	[74448] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Sólido Grande",
			esMX = "Cofre Sólido Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			721,
			491,
		},
	},
	[75293] = {
		names = {
			deDE = "Große Ramponierte Truhe",
			enUS = "Large Battered Chest",
			esES = "Cofre Grande Abollado",
			esMX = "Cofre Grande Abollado",
			frFR = "Grand Coffre Endommagé",
			koKR = "낡은 대형 궤짝",
			ptBR = "Baú Desgastado Grande",
			ruRU = "Большой Побитый Сундук",
			zhCN = "破碎的大箱子",
			zhTW = "破碎的大箱子",
		},
		zones = {
			209,
			718,
			1581,
			2597,
		},
	},
	[75295] = {
		names = {
			deDE = "Große Eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre Reforzado Con Hierro Grande",
			esMX = "Cofre Reforzado Con Hierro Grande",
			frFR = "Grand Coffre Cerclé De Fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой Сундук Окованный Железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			209,
			717,
			719,
		},
	},
	[75296] = {
		names = {
			deDE = "Große Eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre Reforzado Con Hierro Grande",
			esMX = "Cofre Reforzado Con Hierro Grande",
			frFR = "Grand Coffre Cerclé De Fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой Сундук Окованный Железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			796,
		},
	},
	[75297] = {
		names = {
			deDE = "Große Eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre Reforzado Con Hierro Grande",
			esMX = "Cofre Reforzado Con Hierro Grande",
			frFR = "Grand Coffre Cerclé De Fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой Сундук Окованный Железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			796,
			722,
		},
	},
	[75298] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Sólido Grande",
			esMX = "Cofre Sólido Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			209,
			717,
			719,
			2597,
		},
	},
	[75299] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Sólido Grande",
			esMX = "Cofre Sólido Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			796,
			2597,
		},
	},
	[75300] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Sólido Grande",
			esMX = "Cofre Sólido Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			796,
			722,
			2597,
		},
	},
	[105578] = {
		names = {
			deDE = "Truhe Der Horde",
			enUS = "Horde Chest",
			esES = "Cofre De La Horda",
			esMX = "Cofre De La Horda",
			frFR = "Coffre De La Horde",
			koKR = "호드 궤짝",
			ptBR = "Baú da Horda",
			ruRU = "Сундук Орды",
			zhCN = "部落储物箱",
			zhTW = "部落儲物箱",
		},
		zones = {
			45,
		},
	},
	[105579] = {
		names = {
			deDE = "Truhe Der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre De La Alianza",
			esMX = "Cofre De La Alianza",
			frFR = "Coffre De Lalliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			36,
			45,
		},
	},
	[105581] = {
		names = {
			deDE = "Truhe Der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre De La Alianza",
			esMX = "Cofre De La Alianza",
			frFR = "Coffre De Lalliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			45,
		},
	},
	[106318] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Battered Chest",
			esES = "Cofre Maltrecho",
			esMX = "Cofre Maltrecho",
			frFR = "Coffre Endommagé",
			koKR = "낡은 궤짝",
			ptBR = "Baú Desgastado",
			ruRU = "Побитый Сундук",
			zhCN = "破损的箱子",
			zhTW = "破損的箱子",
		},
		zones = {
			14,
			12,
			215,
			1,
			141,
			85,
		},
	},
	[106319] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Battered Chest",
			esES = "Cofre Maltrecho",
			esMX = "Cofre Maltrecho",
			frFR = "Coffre Endommagé",
			koKR = "낡은 궤짝",
			ptBR = "Baú Desgastado",
			ruRU = "Побитый Сундук",
			zhCN = "破损的箱子",
			zhTW = "破損的箱子",
		},
		zones = {
			40,
			38,
			17,
			130,
			148,
		},
	},
	[111095] = {
		names = {
			deDE = "Truhe Der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre De La Alianza",
			esMX = "Cofre De La Alianza",
			frFR = "Coffre De Lalliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			130,
			17,
		},
	},
	[131979] = {
		names = {
			deDE = "Große Dunkelholztruhe",
			enUS = "Large Darkwood Chest",
			esES = "Cofre Grande De Leñoscuro",
			esMX = "Cofre Grande De Leñoscuro",
			frFR = "Grand Coffre De Sombrebois",
			koKR = "큰 흑단 궤짝",
			ptBR = "Baú de Lenhanegra Grande",
			ruRU = "Большой Сундук Темного Леса",
			zhCN = "大型黑木箱",
			zhTW = "大型黑木箱",
		},
		zones = {
			1337,
		},
	},
	[141596] = {
		names = {
			deDE = "Hexendoktors Truhe",
			enUS = "Witch Doctors Chest",
			esES = "Cofre Del Médico Brujo",
			esMX = "Cofre Del Médico Brujo",
			frFR = "Coffre Du Sorcier Docteur",
			koKR = "의술사의 궤짝",
			ptBR = "Baú do Mandingueiro",
			ruRU = "Сундук Знахаря",
			zhCN = "巫医的箱子",
			zhTW = "巫醫的箱子",
		},
		zones = {
			2597,
			1176,
		},
	},
	[141979] = {
		names = {
			deDE = "Antiker Schatz",
			enUS = "Ancient Treasure",
			esES = "Tesoro Antiguo",
			esMX = "Tesoro Antiguo",
			frFR = "Trésor Ancien",
			koKR = "고대의 보물",
			ptBR = "Tesouro Antigo",
			ruRU = "Древнее Сокровище",
			zhCN = "古代宝藏",
			zhTW = "古代寶藏",
		},
		zones = {
			1337,
		},
	},
	[142184] = {
		names = {
			deDE = "Truhe Des Käpt Ns",
			enUS = "Captains Chest",
			esES = "Cofre Del Capitán",
			esMX = "Cofre Del Capitán",
			frFR = "Coffre Du Capitaine",
			koKR = "선장의 궤짝",
			ptBR = "Baú do Capitão",
			ruRU = "Сундук Капитана",
			zhCN = "船长的箱子",
			zhTW = "船長的箱子",
		},
		zones = {
			440,
		},
	},
	[152608] = {
		names = {
			deDE = "Kolkars Beute",
			enUS = "Kolkars Booty",
			esES = "Botín Kolkar",
			esMX = "Botín Kolkar",
			frFR = "Butin Des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim do Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[152618] = {
		names = {
			deDE = "Kolkars Beute",
			enUS = "Kolkars Booty",
			esES = "Botín Kolkar",
			esMX = "Botín Kolkar",
			frFR = "Butin Des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim do Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[153451] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			47,
			16,
			4,
			440,
		},
	},
	[153453] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			46,
			16,
			28,
			139,
		},
	},
	[153454] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre Sólido",
			esMX = "Cofre Sólido",
			frFR = "Coffre Solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный Сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			139,
			618,
		},
	},
	[153463] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Sólido Grande",
			esMX = "Cofre Sólido Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			28,
		},
	},
	[153464] = {
		names = {
			deDE = "Große Robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre Sólido Grande",
			esMX = "Cofre Sólido Grande",
			frFR = "Grand Coffre Solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой Добротный Сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			2557,
			1583,
			2017,
			2597,
		},
	},
	[153468] = {
		names = {
			deDE = "Große Mithrilbeschlagene Truhe",
			enUS = "Large Mithril Bound Chest",
			esES = "Cofre Reforzado Con Mitril Grande",
			esMX = "Cofre Reforzado Con Mitril Grande",
			frFR = "Grand Coffre Cerclé De Mithril",
			koKR = "큰 미스릴 궤짝",
			ptBR = "Baú Grande Reforçado com Mithril",
			ruRU = "Большой Сундук Окованный Мифрилом",
			zhCN = "大型秘银储物箱",
			zhTW = "大型秘銀儲物箱",
		},
		zones = {
			28,
		},
	},
	[153469] = {
		names = {
			deDE = "Große Mithrilbeschlagene Truhe",
			enUS = "Large Mithril Bound Chest",
			esES = "Cofre Reforzado Con Mitril Grande",
			esMX = "Cofre Reforzado Con Mitril Grande",
			frFR = "Grand Coffre Cerclé De Mithril",
			koKR = "큰 미스릴 궤짝",
			ptBR = "Baú Grande Reforçado com Mithril",
			ruRU = "Большой Сундук Окованный Мифрилом",
			zhCN = "大型秘银储物箱",
			zhTW = "大型秘銀儲物箱",
		},
		zones = {
			2557,
			1583,
			2017,
		},
	},
	[160845] = {
		names = {
			deDE = "Dunkler Kasten",
			enUS = "Dark Coffer",
			esES = "Arca Oscura",
			esMX = "Arca Oscura",
			frFR = "Coffre Sombre",
			koKR = "검은 금고",
			ptBR = "Cofre Sombrio",
			ruRU = "Черный Ящик",
			zhCN = "黑暗宝箱",
			zhTW = "黑暗寶箱",
		},
		zones = {
			1584,
		},
	},
	[173232] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
			3358,
			2597,
		},
	},
	[173234] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
		},
	},
	[176224] = {
		names = {
			deDE = "Vorratskiste",
			enUS = "Supply Crate",
			esES = "Cajón De Provisiones",
			esMX = "Cajón De Provisiones",
			frFR = "Caisse De Fournitures",
			koKR = "보급품 상자",
			ptBR = "Caixote de Suprimentos",
			ruRU = "Ящик С Припасами",
			zhCN = "补给箱",
			zhTW = "補給箱",
		},
		zones = {
			2017,
			2597,
		},
	},
	[176325] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[176327] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños De Herrería",
			esMX = "Diseños De Herrería",
			frFR = "Plans De Forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи Кузнечного Дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[179501] = {
		names = {
			deDE = "Knot Thimblejacks Behälter",
			enUS = "Knot Thimblejacks Cache",
			esES = "Alijo De Knot Thimblejack",
			esMX = "Alijo De Knot Thimblejack",
			frFR = "Réserve De Knot Thimblejack",
			koKR = "노트 팀블잭의 은닉품",
			ptBR = "Tesouro do Fiapo Agulhacerta",
			ruRU = "Тайник Уззла Наперстяка",
			zhCN = "诺特 希姆加克的储物箱",
			zhTW = "諾特 希姆加剋的儲物箱",
		},
		zones = {
			2557,
		},
	},
	[179564] = {
		names = {
			deDE = "Tribut Der Gordok",
			enUS = "Gordok Tribute",
			esES = "Tributo A Gordok",
			esMX = "Tributo A Gordok",
			frFR = "Tribut Des Gordok",
			koKR = "고르독 공물",
			ptBR = "Homenagem a Gordok",
			ruRU = "Приношения Клана Гордок",
			zhCN = "戈多克贡品",
			zhTW = "戈多剋貢品",
		},
		zones = {
			2557,
		},
	},
	[179697] = {
		names = {
			deDE = "Arenaschatztruhe",
			enUS = "Arena Treasure Chest",
			esES = "Cofre Del Tesoro De La Arena",
			esMX = "Cofre Del Tesoro De La Arena",
			frFR = "Coffre Au Trésor De Larène",
			koKR = "투기장 보물상자",
			ruRU = "Сундук Арены С Сокровищами",
		},
		zones = {
			33,
		},
	},
	[404352] = {
		names = {
			deDE = "Artefaktlagertruhe",
			enUS = "Artifact Storage",
			esES = "Depósito Del Artefacto",
			esMX = "Depósito Del Artefacto",
			frFR = "Entrepôt De L Artéfact",
			koKR = "유물 보관함",
			ruRU = "Хранилище Артефактов",
		},
		zones = {
			215,
		},
	},
	[407734] = {
		names = {
			deDE = "Knarzklauenkiste",
			enUS = "Gnarlpine Cache",
			esES = "Alijo Tuercepinos",
			esMX = "Alijo Tuercepinos",
			frFR = "Cache Pin Tordu",
			koKR = "나무옹이 보관함",
			ptBR = "Baú Masca-pinho",
			ruRU = "Тайник Кривой Сосны",
		},
		zones = {
			141,
		},
	},
	[415614] = {
		names = {
			enUS = "Mysterious Formulae",
			esES = "Fórmulas Misteriosas",
			esMX = "Fórmulas Misteriosas",
			frFR = "Formules Mystérieuses",
			ruRU = "Таинственные Формулы",
		},
		zones = {
			719,
		},
	},
}