local _, rm = ...

rm.objectDB = {
	[404352] = {
		names = {
			deDE = "Artefaktlagertruhe",
			enUS = "Artifact Storage",
			esES = "Depósito del artefacto",
			esMX = "Depósito del artefacto",
			frFR = "Entrepôt de l’Artéfact",
			koKR = "유물 보관함",
			ruRU = "Хранилище артефактов",
		},
		zones = {
			215,
		},
	},
	[2560] = {
		names = {
			deDE = "Halb vergrabene Flasche",
			enUS = "Half-Buried Bottle",
			esES = "Botella semienterrada",
			esMX = "Botella semienterrada",
			frFR = "Bouteille à moitié ensevelie",
			koKR = "반쯤 묻힌 병",
			ptBR = "Garrafa Semienterrada",
			ruRU = "Полузакопанная бутылка",
			zhCN = "半埋的瓶子",
			zhTW = "半埋的瓶子",
		},
		zones = {
			33,
		},
	},
	[4096] = {
		names = {
			deDE = "Truhe der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre de la Alianza",
			esMX = "Cofre de la Alianza",
			frFR = "Coffre de l'Alliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			267,
		},
	},
	[3715] = {
		names = {
			deDE = "Truhe der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre de la Alianza",
			esMX = "Cofre de la Alianza",
			frFR = "Coffre de l'Alliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			267,
			406,
			17,
		},
	},
	[3714] = {
		names = {
			deDE = "Geldkassette der Allianz",
			enUS = "Alliance Strongbox",
			esES = "Caja fuerte de la Alianza",
			esMX = "Caja fuerte de la Alianza",
			frFR = "Coffre de l'Alliance",
			koKR = "얼라이언스 금고",
			ptBR = "Caixa-forte da Aliança",
			ruRU = "Сейф Альянса",
			zhCN = "联盟保险箱",
			zhTW = "聯盟保險箱",
		},
		zones = {
			17,
		},
	},
	[131979] = {
		names = {
			deDE = "Große Dunkelholztruhe",
			enUS = "Large Darkwood Chest",
			esES = "Cofre grande de Leñoscuro",
			esMX = "Cofre grande de Leñoscuro",
			frFR = "Grand coffre de sombrebois",
			koKR = "큰 흑단 궤짝",
			ptBR = "Baú de Lenhanegra Grande",
			ruRU = "Большой сундук Темного Леса",
			zhCN = "大型黑木箱",
			zhTW = "大型黑木箱",
		},
		zones = {
			1337,
		},
	},
	[141979] = {
		names = {
			deDE = "Antiker Schatz",
			enUS = "Ancient Treasure",
			esES = "Tesoro antiguo",
			esMX = "Tesoro antiguo",
			frFR = "Trésor ancien",
			koKR = "고대의 보물",
			ptBR = "Tesouro Antigo",
			ruRU = "Древнее сокровище",
			zhCN = "古代宝藏",
			zhTW = "古代寶藏",
		},
		zones = {
			1337,
		},
	},
	[141596] = {
		names = {
			deDE = "Hexendoktors Truhe",
			enUS = "Witch Doctor's Chest",
			esES = "Cofre del médico brujo",
			esMX = "Cofre del médico brujo",
			frFR = "Coffre du sorcier-docteur",
			koKR = "의술사의 궤짝",
			ptBR = "Baú do Mandingueiro",
			ruRU = "Сундук знахаря",
			zhCN = "巫医的箱子",
			zhTW = "巫醫的箱子",
		},
		zones = {
			2597,
			1176,
		},
	},
	[75293] = {
		names = {
			deDE = "Große ramponierte Truhe",
			enUS = "Large Battered Chest",
			esES = "Cofre grande abollado",
			esMX = "Cofre grande abollado",
			frFR = "Grand coffre endommagé",
			koKR = "낡은 대형 궤짝",
			ptBR = "Baú Desgastado Grande",
			ruRU = "Большой побитый сундук",
			zhCN = "破碎的大箱子",
			zhTW = "破碎的大箱子",
		},
		zones = {
			209,
			718,
			1581,
			2597,
		},
	},
	[75295] = {
		names = {
			deDE = "Große eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre reforzado con hierro grande",
			esMX = "Cofre reforzado con hierro grande",
			frFR = "Grand coffre cerclé de fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой сундук, окованный железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			209,
			717,
			719,
		},
	},
	[152608] = {
		names = {
			deDE = "Kolkars Beute",
			enUS = "Kolkar's Booty",
			esES = "Botín Kolkar",
			esMX = "Botín Kolkar",
			frFR = "Butin des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim do Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[75296] = {
		names = {
			deDE = "Große eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre reforzado con hierro grande",
			esMX = "Cofre reforzado con hierro grande",
			frFR = "Grand coffre cerclé de fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой сундук, окованный железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			796,
		},
	},
	[75298] = {
		names = {
			deDE = "Große robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre sólido grande",
			esMX = "Cofre sólido grande",
			frFR = "Grand coffre solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой добротный сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			209,
			717,
			719,
			2597,
		},
	},
	[2850] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			11,
			44,
			10,
			331,
			406,
			267,
			17,
		},
	},
	[2852] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			10,
			400,
			11,
			331,
			267,
		},
	},
	[75299] = {
		names = {
			deDE = "Große robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre sólido grande",
			esMX = "Cofre sólido grande",
			frFR = "Grand coffre solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой добротный сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			796,
			2597,
		},
	},
	[75300] = {
		names = {
			deDE = "Große robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre sólido grande",
			esMX = "Cofre sólido grande",
			frFR = "Grand coffre solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой добротный сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			796,
			722,
			2597,
		},
	},
	[2855] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			36,
			33,
			405,
			45,
			267,
			400,
		},
	},
	[2849] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Battered Chest",
			esES = "Cofre maltrecho",
			esMX = "Cofre maltrecho",
			frFR = "Coffre endommagé",
			koKR = "낡은 궤짝",
			ptBR = "Baú Desgastado",
			ruRU = "Побитый сундук",
			zhCN = "破损的箱子",
			zhTW = "破損的箱子",
		},
		zones = {
			44,
			148,
			406,
			17,
			38,
			130,
			331,
			40,
		},
	},
	[2857] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			45,
			405,
			36,
			15,
			3,
			8,
			33,
		},
	},
	[152618] = {
		names = {
			deDE = "Kolkars Beute",
			enUS = "Kolkar's Booty",
			esES = "Botín Kolkar",
			esMX = "Botín Kolkar",
			frFR = "Butin des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim do Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[179501] = {
		names = {
			deDE = "Knot Thimblejacks Behälter",
			enUS = "Knot Thimblejack's Cache",
			esES = "Alijo de Knot Thimblejack",
			esMX = "Alijo de Knot Thimblejack",
			frFR = "Réserve de Knot Thimblejack",
			koKR = "노트 팀블잭의 은닉품",
			ptBR = "Tesouro do Fiapo Agulhacerta",
			ruRU = "Тайник Уззла Наперстяка",
			zhCN = "诺特",
			zhTW = "諾特",
		},
		zones = {
			2557,
		},
	},
	[173232] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños de herrería",
			esMX = "Diseños de herrería",
			frFR = "Plans de forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи кузнечного дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
			3358,
			2597,
		},
	},
	[173234] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños de herrería",
			esMX = "Diseños de herrería",
			frFR = "Plans de forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи кузнечного дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			1584,
		},
	},
	[4149] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			33,
			51,
			440,
			8,
			15,
			47,
			3,
		},
	},
	[407734] = {
		names = {
			deDE = "Knarzklauenkiste",
			enUS = "Gnarlpine Cache",
			esES = "Alijo Tuercepinos",
			esMX = "Alijo Tuercepinos",
			frFR = "Cache pin-tordu",
			koKR = "나무옹이 보관함",
			ptBR = "Baú Masca-pinho",
			ruRU = "Тайник Кривой Сосны",
		},
		zones = {
			141,
		},
	},
	[3642] = {
		names = {
			deDE = "Kolkars Beute",
			enUS = "Kolkars' Booty",
			esES = "Botín Kolkar",
			esMX = "Botín Kolkar",
			frFR = "Butin des Kolkar",
			koKR = "콜카르 노획물 궤짝",
			ptBR = "Butim de Kolkar",
			ruRU = "Добыча Колкара",
			zhCN = "科卡尔的战利品",
			zhTW = "科卡爾的戰利品",
		},
		zones = {
			17,
		},
	},
	[160836] = {
		names = {
			deDE = "Reliktkasten",
			enUS = "Relic Coffer",
			esES = "Arca de reliquias",
			esMX = "Arca de reliquias",
			frFR = "Coffre aux reliques",
			koKR = "유물 금고",
			ptBR = "Arca de Relíquia",
			ruRU = "Реликварий",
			zhCN = "古物宝库",
			zhTW = "古物寶庫",
		},
		zones = {
			1584,
			3277,
			2597,
		},
	},
	[176325] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños de herrería",
			esMX = "Diseños de herrería",
			frFR = "Plans de forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи кузнечного дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[176327] = {
		names = {
			deDE = "Schmiedekunstpläne",
			enUS = "Blacksmithing Plans",
			esES = "Diseños de herrería",
			esMX = "Diseños de herrería",
			frFR = "Plans de forgeron",
			koKR = "대장기술 도면",
			ptBR = "Instruções de Ferraria",
			ruRU = "Чертежи кузнечного дела",
			zhCN = "锻造设计图",
			zhTW = "鍛造設計圖",
		},
		zones = {
			2017,
		},
	},
	[160845] = {
		names = {
			deDE = "Dunkler Kasten",
			enUS = "Dark Coffer",
			esES = "Arca oscura",
			esMX = "Arca oscura",
			frFR = "Coffre sombre",
			koKR = "검은 금고",
			ptBR = "Cofre Sombrio",
			ruRU = "Черный ящик",
			zhCN = "黑暗宝箱",
			zhTW = "黑暗寶箱",
		},
		zones = {
			1584,
		},
	},
	[106318] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Battered Chest",
			esES = "Cofre maltrecho",
			esMX = "Cofre maltrecho",
			frFR = "Coffre endommagé",
			koKR = "낡은 궤짝",
			ptBR = "Baú Desgastado",
			ruRU = "Побитый сундук",
			zhCN = "破损的箱子",
			zhTW = "破損的箱子",
		},
		zones = {
			14,
			12,
			215,
			1,
			141,
			85,
		},
	},
	[106319] = {
		names = {
			deDE = "Ramponierte Truhe",
			enUS = "Battered Chest",
			esES = "Cofre maltrecho",
			esMX = "Cofre maltrecho",
			frFR = "Coffre endommagé",
			koKR = "낡은 궤짝",
			ptBR = "Baú Desgastado",
			ruRU = "Побитый сундук",
			zhCN = "破损的箱子",
			zhTW = "破損的箱子",
		},
		zones = {
			40,
			38,
			17,
			130,
			148,
		},
	},
	[74447] = {
		names = {
			deDE = "Große eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre reforzado con hierro grande",
			esMX = "Cofre reforzado con hierro grande",
			frFR = "Grand coffre cerclé de fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой сундук, окованный железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			491,
		},
	},
	[74448] = {
		names = {
			deDE = "Große robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre sólido grande",
			esMX = "Cofre sólido grande",
			frFR = "Grand coffre solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой добротный сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			721,
			491,
		},
	},
	[75297] = {
		names = {
			deDE = "Große eisenbeschlagene Truhe",
			enUS = "Large Iron Bound Chest",
			esES = "Cofre reforzado con hierro grande",
			esMX = "Cofre reforzado con hierro grande",
			frFR = "Grand coffre cerclé de fer",
			koKR = "큰 철제 궤짝",
			ptBR = "Baú Grande Reforçado com Ferro",
			ruRU = "Большой сундук, окованный железом",
			zhCN = "大型铁箍储物箱",
			zhTW = "大型鐵箍儲物箱",
		},
		zones = {
			796,
			722,
		},
	},
	[176224] = {
		names = {
			deDE = "Vorratskiste",
			enUS = "Supply Crate",
			esES = "Cajón de provisiones",
			esMX = "Cajón de provisiones",
			frFR = "Caisse de fournitures",
			koKR = "보급품 상자",
			ptBR = "Caixote de Suprimentos",
			ruRU = "Ящик с припасами",
			zhCN = "补给箱",
			zhTW = "補給箱",
		},
		zones = {
			2017,
			2597,
		},
	},
	[111095] = {
		names = {
			deDE = "Truhe der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre de la Alianza",
			esMX = "Cofre de la Alianza",
			frFR = "Coffre de l'Alliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			130,
			17,
		},
	},
	[142184] = {
		names = {
			deDE = "Truhe des Käpt’ns",
			enUS = "Captain's Chest",
			esES = "Cofre del Capitán",
			esMX = "Cofre del Capitán",
			frFR = "Coffre du capitaine",
			koKR = "선장의 궤짝",
			ptBR = "Baú do Capitão",
			ruRU = "Сундук капитана",
			zhCN = "船长的箱子",
			zhTW = "船長的箱子",
		},
		zones = {
			440,
		},
	},
	[105578] = {
		names = {
			deDE = "Truhe der Horde",
			enUS = "Horde Chest",
			esES = "Cofre de la Horda",
			esMX = "Cofre de la Horda",
			frFR = "Coffre de la Horde",
			koKR = "호드 궤짝",
			ptBR = "Baú da Horda",
			ruRU = "Сундук Орды",
			zhCN = "部落储物箱",
			zhTW = "部落儲物箱",
		},
		zones = {
			45,
		},
	},
	[153451] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			47,
			16,
			4,
			440,
		},
	},
	[105579] = {
		names = {
			deDE = "Truhe der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre de la Alianza",
			esMX = "Cofre de la Alianza",
			frFR = "Coffre de l'Alliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			36,
			45,
		},
	},
	[105581] = {
		names = {
			deDE = "Truhe der Allianz",
			enUS = "Alliance Chest",
			esES = "Cofre de la Alianza",
			esMX = "Cofre de la Alianza",
			frFR = "Coffre de l'Alliance",
			koKR = "얼라이언스 궤짝",
			ptBR = "Baú da Aliança",
			ruRU = "Сундук Альянса",
			zhCN = "联盟宝箱",
			zhTW = "聯盟寶箱",
		},
		zones = {
			45,
		},
	},
	[153453] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			46,
			16,
			28,
			139,
		},
	},
	[153454] = {
		names = {
			deDE = "Robuste Truhe",
			enUS = "Solid Chest",
			esES = "Cofre sólido",
			esMX = "Cofre sólido",
			frFR = "Coffre solide",
			koKR = "단단한 궤짝",
			ptBR = "Baú Sólido",
			ruRU = "Добротный сундук",
			zhCN = "坚固的箱子",
			zhTW = "堅固的箱子",
		},
		zones = {
			139,
			618,
		},
	},
	[179564] = {
		names = {
			deDE = "Tribut der Gordok",
			enUS = "Gordok Tribute",
			esES = "Tributo a Gordok",
			esMX = "Tributo a Gordok",
			frFR = "Tribut des Gordok",
			koKR = "고르독 공물",
			ptBR = "Homenagem a Gordok",
			ruRU = "Приношения Гордока",
			zhCN = "戈多克贡品",
			zhTW = "戈多剋貢品",
		},
		zones = {
			2557,
		},
	},
	[179697] = {
		names = {
			deDE = "Arenaschatztruhe",
			enUS = "Arena Treasure Chest",
			esES = "Cofre del tesoro de la arena",
			esMX = "Cofre del tesoro de la arena",
			frFR = "Coffre au trésor de l'arène",
			koKR = "투기장 보물상자",
			ruRU = "Сундук Арены с сокровищами",
		},
		zones = {
			33,
		},
	},
	[153463] = {
		names = {
			deDE = "Große robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre sólido grande",
			esMX = "Cofre sólido grande",
			frFR = "Grand coffre solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой добротный сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			28,
		},
	},
	[153464] = {
		names = {
			deDE = "Große robuste Truhe",
			enUS = "Large Solid Chest",
			esES = "Cofre sólido grande",
			esMX = "Cofre sólido grande",
			frFR = "Grand coffre solide",
			koKR = "크고 단단한 궤짝",
			ptBR = "Baú Grande Sólido",
			ruRU = "Большой добротный сундук",
			zhCN = "坚固的大箱子",
			zhTW = "堅固的大箱子",
		},
		zones = {
			2557,
			1583,
			2017,
			2597,
		},
	},
	[153468] = {
		names = {
			deDE = "Große mithrilbeschlagene Truhe",
			enUS = "Large Mithril Bound Chest",
			esES = "Cofre reforzado con mitril grande",
			esMX = "Cofre reforzado con mitril grande",
			frFR = "Grand coffre cerclé de mithril",
			koKR = "큰 미스릴 궤짝",
			ptBR = "Baú Grande Reforçado com Mithril",
			ruRU = "Большой сундук, окованный мифрилом",
			zhCN = "大型秘银储物箱",
			zhTW = "大型秘銀儲物箱",
		},
		zones = {
			28,
		},
	},
	[153469] = {
		names = {
			deDE = "Große mithrilbeschlagene Truhe",
			enUS = "Large Mithril Bound Chest",
			esES = "Cofre reforzado con mitril grande",
			esMX = "Cofre reforzado con mitril grande",
			frFR = "Grand coffre cerclé de mithril",
			koKR = "큰 미스릴 궤짝",
			ptBR = "Baú Grande Reforçado com Mithril",
			ruRU = "Большой сундук, окованный мифрилом",
			zhCN = "大型秘银储物箱",
			zhTW = "大型秘銀儲物箱",
		},
		zones = {
			2557,
			1583,
			2017,
		},
	},
	[415614] = {
		names = {
			enUS = "Mysterious Formulae",
			esES = "Fórmulas misteriosas",
			esMX = "Fórmulas misteriosas",
			frFR = "Formules mystérieuses",
			ruRU = "Таинственные формулы",
		},
		zones = {
			719,
		},
	},
}